### ISSUE TITLE
UF installation, Quickstart Local, localhost:3333/footprint refuse to connect

### ISSUE THREAD

**Issue by Shuake** [CalthorpeAnalytics/urbanfootprint#3] opened 2017-04-11 15:38 UTC
Hello,

I am very new to UF. I followed the quick start guide, downloaded all the prerequisites, successfully lunched UrbanFootprint, but was not able to connect to localhost address. I would appreciate any help. Thanks!

![1](https://cloud.githubusercontent.com/assets/15724132/24917499/070352f8-1ea3-11e7-94d1-dde1fa47517f.PNG)
![2](https://cloud.githubusercontent.com/assets/15724132/24917501/08702634-1ea3-11e7-8358-1a8347cc5b53.PNG)

**Comment by rkain365** [comment] 2017-04-11 21:30
I have the same issue.  Ran Git Bash, ran prompt.  Got confirmation of successful installation.    Same browser error.    When opening up VirtualBox Manager no images present?

![capture](https://cloud.githubusercontent.com/assets/27310338/24931762/5c4be250-1ec3-11e7-95a8-7e93be042707.JPG)

**Comment by rkain365** [comment] 2017-04-12 01:07
I get this error when running the cloud quick start script.  

Failed to fetch http://ppa.launchpad.net/chrislea/node.js/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

![error](https://cloud.githubusercontent.com/assets/27310338/24936861/aa1a368a-1ee1-11e7-823c-0811b9f407c2.JPG)

**Comment by jalessio** [comment] 2017-04-12 01:49
@Shuake I can see from your screenshot (_and from the empty VirtualBox GUI screenshot from @rkain365_) that you are getting a failure before any UF initialization code even runs. It looks like a Vagrant failure. I recommend first making sure you have Vagrant+VirtualBox configured correctly by running the following (slightly modified) instructions from the [Vagrant "Up and Running" docs](https://www.vagrantup.com/intro/getting-started/index.html#up-and-running):

 ```
vagrant init ubuntu/trusty64
vagrant up
```

At that point you should be able to run `vagrant ssh` and you should also see a running VM in the Virtualbox GUI.

**Comment by jalessio** [comment] 2017-04-12 01:51
@rkain365 You're getting that error because you're using Ubuntu 16 (Xenial) instead of Ubuntu 14 (Trusty), as specified in [README-cloud.md](https://github.com/CalthorpeAnalytics/urbanfootprint/blob/master/README-cloud.md):

> A dedicated server running Ubuntu 14.04 that you have ssh access to. On AWS, we recommend "Ubuntu Server 14.04 LTS (HVM), SSD Volume Type"

**Comment by rkain365** [comment] 2017-04-12 16:52
Jamie,

Thanks for getting back to me.   Still not able to access the local host.  I ran the command you listed.    Verified the VM is now present.

[cid:image003.jpg@01D2B372.7E8B2EA0]

Ran the Quickstart Local  command: curl https://raw.githubusercontent.com/CalthorpeAnalytics/urbanfootprint/master/get-uf.sh | bash

Shows that the install was successful but still cannot access the local host?

Attached is the transcript from the GIT Bash.




ROBERT KAIN
Geospatial Services Business Leader

[cid:image006.jpg@01D2B372.7E8B2EA0]<http://www.placeworks.com/>

3 MacArthur Place, Suite 1100 | Santa Ana, California 92707
714.966.9220 | rkain@placeworks.com<mailto:rkain@placeworks.com> | placeworks.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.placeworks.com_&d=DwMFAg&c=n6-cguzQvX_tUIrZOS_4Og&r=6pYjEEvBkEgFMkqes1ivvFCiiO0tnGmx3oNiiYCDFiA&m=UrZEVghSrqiLX6iCMAxICp-fhqF-SnVh--Y-HyNyL5E&s=vLF8JOKghUqDXRtpPQwyzK_p2lIYC4W__MTbUWZ6M1c&e=>

**Comment by jalessio** [comment] 2017-04-12 17:54
@rkain365 looks like you responded via email to the github issue and the images didn't make it through.

**Comment by rkain365** [comment] 2017-04-12 17:59
Here is the transcript of the email response and attachment.

ROBERT KAIN
Geospatial Services Business Leader

[cid:image002.jpg@01D2B37B.C4099F80]<http://www.placeworks.com/>

3 MacArthur Place, Suite 1100 | Santa Ana, California 92707
714.966.9220 | rkain@placeworks.com<mailto:rkain@placeworks.com> | placeworks.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.placeworks.com_&d=DwMFAg&c=n6-cguzQvX_tUIrZOS_4Og&r=6pYjEEvBkEgFMkqes1ivvFCiiO0tnGmx3oNiiYCDFiA&m=UrZEVghSrqiLX6iCMAxICp-fhqF-SnVh--Y-HyNyL5E&s=vLF8JOKghUqDXRtpPQwyzK_p2lIYC4W__MTbUWZ6M1c&e=>

-----------------------------------------------------------------------------------------------------

Jamie,

Thanks for getting back to me.   Still not able to access the local host.  I ran the command you listed.    Verified the VM is now present.

[cid:image003.jpg@01D2B37B.C4099F80]

Ran the Quickstart Local  command: curl https://raw.githubusercontent.com/CalthorpeAnalytics/urbanfootprint/master/get-uf.sh | bash

Shows that the install was successful but still cannot access the local host?

Attached is the transcript from the GIT Bash.

**Comment by rkain365** [comment] 2017-04-12 18:48
Thanks for getting back to me.   Still not able to access the local host.  I ran the command you listed.    Verified the VM is now present.   

[Install Log.docx](https://github.com/CalthorpeAnalytics/urbanfootprint/files/917529/Install.Log.docx)

Ran the Quickstart Local  command: curl https://raw.githubusercontent.com/CalthorpeAnalytics/urbanfootprint/master/get-uf.sh | bash

Shows that the install was successful but still cannot access the local host?

Attached is the transcript from the GIT Bash.

**Comment by jalessio** [comment] 2017-04-17 20:36
I was able to reproduce the issue locally on a Windows machine running the latest Virtualbox and Vagrant versions. 

The cause appears to be an issue with Vagrant version 1.9.3 _(which I can see @rkain365 is using via the logs provided)_: mitchellh/vagrant#8395. The issue has been fixed in the Vagrant repo (via mitchellh/vagrant#8399), but hasn't made its way into a public release yet so it's not possible to easily download an updated version of Vagrant.

In the meantime, I should be able to make a small change to the "pre-built" `Vagrantfile` in order to get this working again.

**Comment by jalessio** [comment] 2017-04-17 23:16
@rkain365 and @Shuake please try installation again -- I believe this issue was address by PR's #4  and #5

**Comment by rkain365** [comment] 2017-04-19 19:58
Ran through the process again this morning and now have a working VM and can access the local instance of UF. Thanks!!

**Comment by jalessio** [comment] 2017-04-19 23:33
Closing per PR #4 and #5.

**Closed as completed by jalessio** 2017-04-19 23:33 UTC
